# Generated by Django 3.1.7 on 2021-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
