# Generated by Django 3.1.7 on 2021-05-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seats', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.usermodel')),
                ('position', models.CharField(max_length=3)),
                ('status', models.CharField(default='miss', max_length=10)),
                ('cls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seats.classmodel')),
            ],
        ),
    ]
