# Generated by Django 3.1.7 on 2021-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatsModel',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seats', models.TextField()),
            ],
        ),
    ]
