# Generated by Django 3.1.7 on 2021-04-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210325_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seats', models.TextField(default='[["miss", "miss", "miss", "miss", "miss"], ["miss", "miss", "miss", "miss", "miss"], ["miss", "miss", "miss", "miss", "miss"], ["miss", "miss", "miss", "miss", "miss"], ["miss", "miss", "miss", "miss", "miss"]]')),
            ],
        ),
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=3)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.classmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='SeatsModel',
        ),
    ]
