# Generated by Django 3.1.7 on 2021-04-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210415_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmodel',
            name='status',
            field=models.CharField(default='miss', max_length=10),
        ),
    ]
