# Generated by Django 3.1.7 on 2021-04-15 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_seatmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmodel',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
