# Generated by Django 3.1.7 on 2021-04-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210415_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatmodel',
            old_name='class_id',
            new_name='cls',
        ),
        migrations.RenameField(
            model_name='seatmodel',
            old_name='student_id',
            new_name='student',
        ),
    ]
